export type LeadWorkspaceItem = {
  id: string;
  nome: string;
  telefone: string;
  status: string;
  qualificationStatus: string;
  qualificationState?: string | null;
  distributionStatus?: string;
  origem: string;
  email?: string | null;
  sourceChannel?: string | null;
  sourceCampaign: string | null;
  sourceMetadata?: unknown;
  /** Tags the team put on this lead's conversation. */
  tags?: { id: string; name: string; colorHue: number }[];
  tipo: string;
  createdAt: string;
  assignedAt: string | null;
  stageEnteredAt: string | null;
  serviceStartedAt: string | null;
  firstContactAt: string | null;
  corretorId: string | null;
  corretorNome: string | null;
  isPlantaoAtivo?: boolean;
  returnedUnaccepted?: boolean;
  isManagementInvestigation?: boolean;
  branchId: string | null;
  branchName: string | null;
  qualificationDetails?: Record<string, unknown> | null;
  queueId?: string | null;
  queueName?: string | null;
  queueColorHue?: number | null;
  distributionRemovalReason?: string | null;
  distributionRemovalNote?: string | null;
};
