CREATE INDEX IF NOT EXISTS "active_customers_broker_id_idx" ON "active_customers" USING btree ("broker_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "active_customers_client_id_idx" ON "active_customers" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "active_customers_lead_id_idx" ON "active_customers" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "agent_behavior_versions_created_by_idx" ON "agent_behavior_versions" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "agent_behavior_versions_published_by_idx" ON "agent_behavior_versions" USING btree ("published_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "agent_evaluation_runs_agent_id_idx" ON "agent_evaluation_runs" USING btree ("agent_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "agent_evaluation_runs_tenant_id_idx" ON "agent_evaluation_runs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "agent_training_simulations_behavior_version_id_idx" ON "agent_training_simulations" USING btree ("behavior_version_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "agent_training_simulations_created_by_idx" ON "agent_training_simulations" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_conversations_behavior_version_id_idx" ON "ai_conversations" USING btree ("behavior_version_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_qualification_configs_updated_by_idx" ON "ai_qualification_configs" USING btree ("updated_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_qualification_sessions_lead_id_idx" ON "ai_qualification_sessions" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_qualification_test_numbers_owner_user_id_idx" ON "ai_qualification_test_numbers" USING btree ("owner_user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_quick_reply_events_lead_id_idx" ON "ai_quick_reply_events" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_quick_reply_events_notified_user_id_idx" ON "ai_quick_reply_events" USING btree ("notified_user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "ai_quick_reply_templates_updated_by_idx" ON "ai_quick_reply_templates" USING btree ("updated_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "branch_catalog_plan_restrictions_global_plan_id_idx" ON "branch_catalog_plan_restrictions" USING btree ("global_plan_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "branch_catalog_plan_restrictions_updated_by_idx" ON "branch_catalog_plan_restrictions" USING btree ("updated_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "carrier_plan_networks_tenant_id_idx" ON "carrier_plan_networks" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "carrier_plan_prices_tenant_id_idx" ON "carrier_plan_prices" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "catalog_change_sets_created_by_idx" ON "catalog_change_sets" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "catalog_change_sets_import_batch_id_idx" ON "catalog_change_sets" USING btree ("import_batch_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "catalog_change_sets_reviewed_by_idx" ON "catalog_change_sets" USING btree ("reviewed_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "catalog_import_batches_created_by_idx" ON "catalog_import_batches" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "catalog_price_tables_created_by_idx" ON "catalog_price_tables" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "catalog_table_versions_published_by_idx" ON "catalog_table_versions" USING btree ("published_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "clients_branch_id_idx" ON "clients" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "commission_rules_created_by_idx" ON "commission_rules" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "commission_schedule_paid_by_idx" ON "commission_schedule" USING btree ("paid_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "communication_channels_created_by_idx" ON "communication_channels" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "communication_channels_owner_user_id_idx" ON "communication_channels" USING btree ("owner_user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "companies_branch_id_idx" ON "companies" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "companies_created_by_idx" ON "companies" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "conversation_examples_tenant_id_idx" ON "conversation_examples" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "crm_automation_logs_automation_id_idx" ON "crm_automation_logs" USING btree ("automation_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "crm_automation_logs_client_id_idx" ON "crm_automation_logs" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "crm_automation_logs_lead_id_idx" ON "crm_automation_logs" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "crm_automation_logs_tenant_id_idx" ON "crm_automation_logs" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "crm_automations_created_by_idx" ON "crm_automations" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "custom_role_events_actor_user_id_idx" ON "custom_role_events" USING btree ("actor_user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "custom_role_events_tenant_id_idx" ON "custom_role_events" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "custom_roles_created_by_idx" ON "custom_roles" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "customer_renewal_reminders_active_customer_id_idx" ON "customer_renewal_reminders" USING btree ("active_customer_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "customer_renewal_reminders_broker_id_idx" ON "customer_renewal_reminders" USING btree ("broker_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "customer_renewal_reminders_client_id_idx" ON "customer_renewal_reminders" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "customer_renewal_reminders_sale_id_idx" ON "customer_renewal_reminders" USING btree ("sale_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_requirements_carrier_id_idx" ON "document_requirements" USING btree ("carrier_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "document_requirements_plan_id_idx" ON "document_requirements" USING btree ("plan_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "duty_roster_assignments_branch_id_idx" ON "duty_roster_assignments" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "duty_roster_assignments_broker_id_idx" ON "duty_roster_assignments" USING btree ("broker_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "duty_roster_assignments_created_by_idx" ON "duty_roster_assignments" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "duty_roster_assignments_updated_by_idx" ON "duty_roster_assignments" USING btree ("updated_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "evaluation_test_cases_agent_id_idx" ON "evaluation_test_cases" USING btree ("agent_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "evaluation_test_cases_tenant_id_idx" ON "evaluation_test_cases" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "extension_auth_codes_tenant_id_idx" ON "extension_auth_codes" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "extension_auth_codes_user_id_idx" ON "extension_auth_codes" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "extension_settings_updated_by_idx" ON "extension_settings" USING btree ("updated_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "feedback_checklist_items_tenant_id_idx" ON "feedback_checklist_items" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "feedback_checklist_templates_created_by_idx" ON "feedback_checklist_templates" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "global_carriers_created_by_idx" ON "global_carriers" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "global_plans_created_by_idx" ON "global_plans" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "goals_created_by_idx" ON "goals" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "internal_report_documents_uploaded_by_idx" ON "internal_report_documents" USING btree ("uploaded_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "invites_invited_by_idx" ON "invites" USING btree ("invited_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "knowledge_chunks_document_id_idx" ON "knowledge_chunks" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "knowledge_documents_collection_id_idx" ON "knowledge_documents" USING btree ("collection_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "knowledge_documents_source_id_idx" ON "knowledge_documents" USING btree ("source_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "knowledge_suggestions_source_id_idx" ON "knowledge_suggestions" USING btree ("source_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_assignment_attempts_broker_id_idx" ON "lead_assignment_attempts" USING btree ("broker_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_distribution_events_actor_id_idx" ON "lead_distribution_events" USING btree ("actor_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_distribution_events_lead_id_idx" ON "lead_distribution_events" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_distribution_jobs_lead_id_idx" ON "lead_distribution_jobs" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_distribution_policies_queue_id_idx" ON "lead_distribution_policies" USING btree ("queue_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_distribution_policies_updated_by_idx" ON "lead_distribution_policies" USING btree ("updated_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_distribution_settings_branch_id_idx" ON "lead_distribution_settings" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_distribution_settings_queue_id_idx" ON "lead_distribution_settings" USING btree ("queue_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_distribution_settings_updated_by_idx" ON "lead_distribution_settings" USING btree ("updated_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_document_checklist_beneficiary_id_idx" ON "lead_document_checklist" USING btree ("beneficiary_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_document_checklist_document_id_idx" ON "lead_document_checklist" USING btree ("document_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_document_checklist_lead_id_idx" ON "lead_document_checklist" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_document_checklist_requirement_id_idx" ON "lead_document_checklist" USING btree ("requirement_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_documents_client_id_idx" ON "lead_documents" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_documents_deleted_by_idx" ON "lead_documents" USING btree ("deleted_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_documents_lead_id_idx" ON "lead_documents" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_documents_requirement_id_idx" ON "lead_documents" USING btree ("requirement_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_documents_reviewed_by_idx" ON "lead_documents" USING btree ("reviewed_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_documents_uploaded_by_idx" ON "lead_documents" USING btree ("uploaded_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_effect_outbox_lead_id_idx" ON "lead_effect_outbox" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_effect_outbox_webhook_delivery_id_idx" ON "lead_effect_outbox" USING btree ("webhook_delivery_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_feedbacks_broker_id_idx" ON "lead_feedbacks" USING btree ("broker_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_feedbacks_checklist_id_idx" ON "lead_feedbacks" USING btree ("checklist_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_feedbacks_tenant_id_idx" ON "lead_feedbacks" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_interactions_user_id_idx" ON "lead_interactions" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_offers_lead_id_idx" ON "lead_offers" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_offers_outbound_message_id_idx" ON "lead_offers" USING btree ("outbound_message_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_queues_branch_id_idx" ON "lead_queues" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_task_assignees_user_id_idx" ON "lead_task_assignees" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_tasks_created_by_idx" ON "lead_tasks" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "lead_tasks_lead_id_idx" ON "lead_tasks" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "leads_deleted_by_idx" ON "leads" USING btree ("deleted_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "leads_service_started_by_idx" ON "leads" USING btree ("service_started_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "marketing_import_results_lead_id_idx" ON "marketing_import_results" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "marketing_imports_branch_id_idx" ON "marketing_imports" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "marketing_imports_user_id_idx" ON "marketing_imports" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "message_templates_created_by_idx" ON "message_templates" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meta_ad_accounts_connection_id_idx" ON "meta_ad_accounts" USING btree ("connection_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meta_ad_queue_routes_created_by_idx" ON "meta_ad_queue_routes" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meta_ad_queue_routes_queue_id_idx" ON "meta_ad_queue_routes" USING btree ("queue_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meta_campaign_queue_routes_created_by_idx" ON "meta_campaign_queue_routes" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meta_campaign_queue_routes_queue_id_idx" ON "meta_campaign_queue_routes" USING btree ("queue_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meta_connection_attempts_user_id_idx" ON "meta_connection_attempts" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meta_connections_created_by_idx" ON "meta_connections" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meta_integration_settings_created_by_idx" ON "meta_integration_settings" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meta_lead_ad_sources_created_by_idx" ON "meta_lead_ad_sources" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meta_pages_connection_id_idx" ON "meta_pages" USING btree ("connection_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "meta_whatsapp_template_usages_template_id_idx" ON "meta_whatsapp_template_usages" USING btree ("template_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "notifications_lead_id_idx" ON "notifications" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "password_reset_requests_reviewed_by_idx" ON "password_reset_requests" USING btree ("reviewed_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "performance_awards_created_by_idx" ON "performance_awards" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "performance_seasons_closed_by_idx" ON "performance_seasons" USING btree ("closed_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "performance_seasons_created_by_idx" ON "performance_seasons" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "plans_tenant_id_idx" ON "plans" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "platform_purge_jobs_actor_user_id_idx" ON "platform_purge_jobs" USING btree ("actor_user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "post_sale_settings_updated_by_idx" ON "post_sale_settings" USING btree ("updated_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "promotional_materials_created_by_idx" ON "promotional_materials" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "proposals_converted_sale_id_idx" ON "proposals" USING btree ("converted_sale_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "proposals_created_by_idx" ON "proposals" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "proposals_lead_id_idx" ON "proposals" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "proposals_quote_id_idx" ON "proposals" USING btree ("quote_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "quote_line_items_beneficiary_id_idx" ON "quote_line_items" USING btree ("beneficiary_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "quote_line_items_plan_id_idx" ON "quote_line_items" USING btree ("plan_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "quotes_created_by_idx" ON "quotes" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "quotes_lead_id_idx" ON "quotes" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "route_onboarding_progress_user_id_idx" ON "route_onboarding_progress" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sales_carrier_plan_id_idx" ON "sales" USING btree ("carrier_plan_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sales_client_id_idx" ON "sales" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sales_commission_rule_id_idx" ON "sales" USING btree ("commission_rule_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sales_confirmation_document_id_idx" ON "sales" USING btree ("confirmation_document_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "sales_created_by_idx" ON "sales" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tenant_catalog_plan_settings_global_plan_id_idx" ON "tenant_catalog_plan_settings" USING btree ("global_plan_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tenant_catalog_plan_settings_updated_by_idx" ON "tenant_catalog_plan_settings" USING btree ("updated_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tenant_custom_role_settings_updated_by_idx" ON "tenant_custom_role_settings" USING btree ("updated_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tenant_private_carriers_created_by_idx" ON "tenant_private_carriers" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tenant_private_plans_created_by_idx" ON "tenant_private_plans" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tenant_private_price_tables_created_by_idx" ON "tenant_private_price_tables" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "tenant_private_table_versions_published_by_idx" ON "tenant_private_table_versions" USING btree ("published_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "unit_duty_schedules_branch_id_idx" ON "unit_duty_schedules" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "unit_duty_schedules_created_by_idx" ON "unit_duty_schedules" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "unit_duty_schedules_queue_id_idx" ON "unit_duty_schedules" USING btree ("queue_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "unit_duty_schedules_webhook_credential_id_idx" ON "unit_duty_schedules" USING btree ("webhook_credential_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "unit_intelligence_profiles_branch_id_idx" ON "unit_intelligence_profiles" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "user_onboarding_progress_user_id_idx" ON "user_onboarding_progress" USING btree ("user_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "waha_cadence_runs_cadence_id_idx" ON "waha_cadence_runs" USING btree ("cadence_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "waha_cadence_runs_waha_number_id_idx" ON "waha_cadence_runs" USING btree ("waha_number_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "waha_cadence_versions_created_by_idx" ON "waha_cadence_versions" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "waha_cadence_versions_tenant_id_idx" ON "waha_cadence_versions" USING btree ("tenant_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "waha_cadence_versions_waha_number_id_idx" ON "waha_cadence_versions" USING btree ("waha_number_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "waha_cadences_branch_id_idx" ON "waha_cadences" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "waha_cadences_created_by_idx" ON "waha_cadences" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "waha_delivery_outbox_run_id_idx" ON "waha_delivery_outbox" USING btree ("run_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "waha_delivery_outbox_waha_number_id_idx" ON "waha_delivery_outbox" USING btree ("waha_number_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "waha_numbers_branch_id_idx" ON "waha_numbers" USING btree ("branch_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "waha_numbers_created_by_idx" ON "waha_numbers" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "waha_suppressions_created_by_idx" ON "waha_suppressions" USING btree ("created_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "webhook_deliveries_lead_id_idx" ON "webhook_deliveries" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "whatsapp_messages_client_id_idx" ON "whatsapp_messages" USING btree ("client_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "whatsapp_messages_communication_channel_id_idx" ON "whatsapp_messages" USING btree ("communication_channel_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "whatsapp_messages_lead_id_idx" ON "whatsapp_messages" USING btree ("lead_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "whatsapp_outbound_messages_channel_id_idx" ON "whatsapp_outbound_messages" USING btree ("channel_id");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "whatsapp_outbound_messages_requested_by_idx" ON "whatsapp_outbound_messages" USING btree ("requested_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "workflow_automation_versions_published_by_idx" ON "workflow_automation_versions" USING btree ("published_by");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "workflow_automations_created_by_idx" ON "workflow_automations" USING btree ("created_by");
