import Link from "next/link";
import { ArrowUpRight, ChartBar, CheckCircle, ShieldStar, Users, Warning } from "@/components/huge-icons";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { PeriodSelect } from "@/components/period-select";
import type { DashboardViewData } from "../service";

const statusLabel: Record<string, string> = { new: "Novo", distributed: "Distribuído", in_contact: "Em atendimento", quote_sent: "Proposta", negotiation: "Negociação", converted: "Convertido", lost: "Perdido" };
const qualificationLabel: Record<string, string> = { qualified: "Qualificado", hot: "Quente", warm: "Morno", cold: "Frio", pending: "Pendente", qualifying: "Em qualificação", disqualified: "Desqualificado" };
const fmtDate = (value: string) => new Intl.DateTimeFormat("pt-BR", { day: "2-digit", month: "2-digit", hour: "2-digit", minute: "2-digit" }).format(new Date(value));

export function OperationalDashboard({ model, period }: { model: DashboardViewData; period: number }) {
  const maxTrend = Math.max(1, ...model.trend.map((point) => point.received));
  return <main className="flex min-h-full flex-col gap-5 bg-background p-(--mobile-page-padding) sm:gap-6 lg:p-6">
    <header className="flex flex-col gap-4 border-b border-border/70 pb-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">Operação comercial</p><h1 className="text-2xl font-semibold tracking-tight">{model.header.title}</h1><p className="text-sm text-muted-foreground">{model.header.description}</p><p className="mt-2 text-xs text-success">● Dados atualizados agora</p></div><div className="flex flex-wrap items-center gap-2"><Button render={<Link href="/leads" />} variant="outline" size="sm">Abrir leads <ArrowUpRight className="size-3.5" /></Button><Button render={<Link href="/relatorios" />} variant="outline" size="sm">Relatórios <ArrowUpRight className="size-3.5" /></Button><PeriodSelect value={period as 7 | 14 | 30 | 90} label="Período do dashboard" /></div></header>
    <section aria-label="Indicadores do período" className="grid grid-cols-2 gap-3 lg:grid-cols-4">{model.metrics.map((metric) => <Card key={metric.id} className="shadow-none"><CardContent className="p-4"><p className="text-xs text-muted-foreground">{metric.label}</p><p className="mt-2 font-mono text-2xl font-semibold">{metric.value}</p><p className="mt-1 text-xs text-muted-foreground">{metric.description}</p></CardContent></Card>)}</section>
    <section className="grid gap-5 lg:grid-cols-[1.35fr_1fr]"><Card className="shadow-none"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><ChartBar className="size-4 text-primary" /> Leads recebidos no período</CardTitle></CardHeader><CardContent><div className="flex h-36 items-end gap-1.5">{model.trend.map((point) => <div key={point.date} className="flex min-w-0 flex-1 flex-col items-center gap-1"><span className="text-[10px] font-medium">{point.received || ""}</span><div className="w-full rounded-t bg-primary/75" style={{ height: `${Math.max(4, (point.received / maxTrend) * 100)}%` }} title={`${point.received} leads em ${point.date}`} /><span className="text-[9px] text-muted-foreground">{point.date.slice(8)}</span></div>)}</div></CardContent></Card><Card className="shadow-none"><CardHeader><CardTitle className="flex items-center gap-2 text-base"><Warning className="size-4 text-warning" /> Atenção agora</CardTitle></CardHeader><CardContent className="space-y-2">{model.attention.length ? model.attention.map((item) => <Link key={item.id} href={item.href} className="flex items-center justify-between rounded-lg border border-border/70 px-3 py-2.5 hover:bg-muted/40"><span className="truncate text-sm font-medium">{item.title}</span><Badge variant={item.tone === "danger" ? "destructive" : "warning"}>{item.count}</Badge></Link>) : <div className="flex items-center gap-2 rounded-lg bg-success/10 px-3 py-3 text-sm text-success"><CheckCircle className="size-4" /> Nenhuma exceção operacional.</div>}</CardContent></Card></section>
    <section className="grid gap-5 lg:grid-cols-2"><RankCard title="Unidades por leads recebidos" icon={<Users className="size-4 text-primary" />} rows={model.units.map((row) => ({ label: row.name, value: row.received, suffix: `${row.converted} convertidos` }))} /><RankCard title="Top corretores" icon={<ShieldStar className="size-4 text-primary" />} rows={model.brokers.map((row) => ({ label: row.name, value: row.received, suffix: `${row.rate}% conversão` }))} /></section>
    <section className="grid gap-5 lg:grid-cols-3"><Card className="shadow-none"><CardHeader><CardTitle className="text-base">Qualificações no período</CardTitle></CardHeader><CardContent className="space-y-2">{model.qualifications.length ? model.qualifications.map((row) => <div key={row.status} className="flex items-center justify-between text-sm"><span>{qualificationLabel[row.status] ?? row.status}</span><Badge variant="secondary">{row.count}</Badge></div>) : <p className="text-sm text-muted-foreground">Nenhum dado no período.</p>}</CardContent></Card><RecentCard title="Últimos leads" href="/leads" rows={model.recentLeads.map((row) => ({ id: row.id, label: row.name, detail: `${statusLabel[row.status] ?? row.status} · ${row.branchName ?? "Sem unidade"}`, date: fmtDate(row.createdAt) }))} /><RecentCard title="Últimas vendas" href="/vendas" rows={model.recentSales.map((row) => ({ id: row.id, label: row.leadName, detail: row.value ? row.value.toLocaleString("pt-BR", { style: "currency", currency: "BRL" }) : "Venda registrada", date: fmtDate(row.saleDate) }))} /></section>
  </main>;
}
function RankCard({ title, icon, rows }: { title: string; icon: React.ReactNode; rows: Array<{ label: string; value: number; suffix: string }> }) { const max = Math.max(1, ...rows.map((row) => row.value)); return <Card className="shadow-none"><CardHeader><CardTitle className="flex items-center gap-2 text-base">{icon}{title}</CardTitle></CardHeader><CardContent className="space-y-3">{rows.length ? rows.map((row) => <div key={row.label}><div className="flex items-center justify-between gap-3 text-sm"><span className="truncate">{row.label}</span><span className="shrink-0 font-mono font-semibold">{row.value}</span></div><div className="mt-1 h-1.5 rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${Math.max(4, row.value / max * 100)}%` }} /></div><p className="mt-0.5 text-[11px] text-muted-foreground">{row.suffix}</p></div>) : <p className="text-sm text-muted-foreground">Nenhum dado no período.</p>}</CardContent></Card>; }
function RecentCard({ title, href, rows }: { title: string; href: string; rows: Array<{ id: string; label: string; detail: string; date: string }> }) { return <Card className="shadow-none"><CardHeader><CardTitle className="flex items-center justify-between text-base">{title}<Link href={href} className="text-xs font-medium text-primary">Ver todos <ArrowUpRight className="inline size-3" /></Link></CardTitle></CardHeader><CardContent className="space-y-3">{rows.length ? rows.map((row) => <div key={row.id} className="flex items-center justify-between gap-3"><div className="min-w-0"><p className="truncate text-sm font-medium">{row.label}</p><p className="truncate text-xs text-muted-foreground">{row.detail}</p></div><time className="shrink-0 text-[11px] text-muted-foreground">{row.date}</time></div>) : <p className="text-sm text-muted-foreground">Nenhum registro no período.</p>}</CardContent></Card>; }
