import { type PermissionKey } from "@/shared/auth/permissions";

export type FeatureIndexItem = {
  id: string;
  title: string;
  description: string;
  keywords: string[];
  url: string;
  domain: "Visão Geral" | "Comercial" | "Automação" | "Gestão" | "Operação" | "Administração";
  permission: PermissionKey;
  iconName: string;
};

export const FEATURE_SEARCH_INDEX: FeatureIndexItem[] = [
  {
    id: "dashboard",
    title: "Resumo da Operação",
    description: "Visão geral executiva com KPIs de leads, vendas e indicadores em tempo real.",
    keywords: ["dashboard", "home", "resumo", "kpi", "vendas", "faturamento"],
    url: "/dashboard",
    domain: "Visão Geral",
    permission: "acessar_dashboard",
    iconName: "House",
  },
  {
    id: "leads_all",
    title: "Gestão de Leads",
    description: "Lista completa de oportunidades comercial, filtros por status e temperatura.",
    keywords: ["leads", "oportunidades", "funil", "contatos", "prospecção"],
    url: "/leads",
    domain: "Comercial",
    permission: "acessar_leads",
    iconName: "Users",
  },
  {
    id: "leads_minha_fila",
    title: "Minha Fila de Leads",
    description: "Leads atribuídos a você aguardando atendimento imediato.",
    keywords: ["fila", "minha fila", "meus leads", "atendimento", "pendente"],
    url: "/leads?tab=minha-fila",
    domain: "Comercial",
    permission: "acessar_leads",
    iconName: "Users",
  },
  {
    id: "leads_distribuicao",
    title: "Regras de Distribuição de Leads",
    description: "Configuração de filas, prioridades, distribuição automática e fallback.",
    keywords: ["distribuição", "roleta", "encaminhamento", "regras", "fila"],
    url: "/leads?tab=distribuicao",
    domain: "Comercial",
    permission: "leads_reassign",
    iconName: "Redistribute",
  },
  {
    id: "leads_plantao",
    title: "Plantão ao Vivo",
    description: "Monitoramento de corretores logados e escala de plantão em tempo real.",
    keywords: ["plantão", "escala", "ao vivo", "corretores ativos", "presença"],
    url: "/leads?tab=plantao",
    domain: "Comercial",
    permission: "duty_schedules_manage",
    iconName: "WifiHigh",
  },
  {
    id: "conversas",
    title: "Central de Conversas",
    description: "Histórico completo e atendimento via WhatsApp integrado.",
    keywords: ["conversas", "chat", "whatsapp", "mensagens", "atendimento"],
    url: "/conversas",
    domain: "Comercial",
    permission: "acessar_conversas",
    iconName: "ChatCircleText",
  },
  {
    id: "clientes",
    title: "Base de Clientes",
    description: "Gestão de carteira de clientes ativos e controle de renovação.",
    keywords: ["clientes", "carteira", "contratos ativos", "renovações", "apólices"],
    url: "/clientes",
    domain: "Comercial",
    permission: "acessar_clientes",
    iconName: "Handshake",
  },
  {
    id: "vendas",
    title: "Vendas e Propostas",
    description: "Histórico de vendas fechadas e acompanhamento da esteira de propostas.",
    keywords: ["vendas", "propostas", "contratos", "fechamento", "faturamento"],
    url: "/vendas",
    domain: "Comercial",
    permission: "acessar_vendas",
    iconName: "CurrencyCircleDollar",
  },
  {
    id: "cotacao",
    title: "Cotações e Simulador",
    description: "Simulador de planos de saúde, tabelas PME e regras de aceitação.",
    keywords: ["cotação", "simulador", "tabelas", "preços", "pme", "individual"],
    url: "/cotacao",
    domain: "Comercial",
    permission: "acessar_cotacoes",
    iconName: "SlidersHorizontal",
  },
  {
    id: "qualificacao",
    title: "Qualificação IA",
    description: "Central de qualificação automática, diagnóstico WhatsApp, MCP e alertas.",
    keywords: ["qualificação", "ia", "bot", "treinamento", "prompt", "mcp", "resetar memória"],
    url: "/qualificacao",
    domain: "Automação",
    permission: "acessar_qualificacao_ia",
    iconName: "Target",
  },
  {
    id: "qualificacao_followup",
    title: "Regras de Follow-up IA",
    description: "Configuração de disparos automáticos para retomar conversas inativas.",
    keywords: ["followup", "reengajamento", "recuperação", "inativo", "regras"],
    url: "/qualificacao?tab=followup_rules",
    domain: "Automação",
    permission: "acessar_qualificacao_ia",
    iconName: "Clock",
  },
  {
    id: "qualificacao_memory",
    title: "Resetar Memória IA",
    description: "Inspetor e limpeza da memória de atendimento simulado da IA.",
    keywords: ["memória", "resetar memória ia", "limpar contexto", "diagnóstico"],
    url: "/qualificacao?tab=simulator",
    domain: "Automação",
    permission: "acessar_qualificacao_ia",
    iconName: "RotateCcw",
  },
  {
    id: "automacoes",
    title: "Automações & Regras",
    description: "Disparos por evento, webhooks e automação de jornada do cliente.",
    keywords: ["automação", "triggers", "webhooks", "fluxos", "gatilhos"],
    url: "/automacoes",
    domain: "Automação",
    permission: "acessar_configuracoes",
    iconName: "SlidersHorizontal",
  },
  {
    id: "equipe",
    title: "Gestão de Equipe",
    description: "Gerenciamento de corretores, supervisores e convites de novos usuários.",
    keywords: ["equipe", "corretores", "convites", "usuários", "acesso"],
    url: "/equipe",
    domain: "Gestão",
    permission: "convidar_corretor",
    iconName: "Users",
  },
  {
    id: "metas",
    title: "Metas Comerciais",
    description: "Acompanhamento de metas individuais e por filial.",
    keywords: ["metas", "objetivo", "desempenho", "alvo", "minha meta"],
    url: "/metas",
    domain: "Gestão",
    permission: "gerenciar_metas",
    iconName: "Target",
  },
  {
    id: "relatorios",
    title: "Relatórios & BI",
    description: "Análise de conversão, tempos de SLA e custos daoperação de IA.",
    keywords: ["relatórios", "métrica", "custos ia", "conversão", "bi", "dados"],
    url: "/dashboard",
    domain: "Gestão",
    permission: "acessar_relatorios",
    iconName: "ChartBar",
  },
  {
    id: "tarefas",
    title: "Gestão de Tarefas",
    description: "Lembretes, retornos agendados e compromissos operacionais.",
    keywords: ["tarefas", "agenda", "lembretes", "compromissos", "retornos"],
    url: "/tarefas",
    domain: "Operação",
    permission: "acessar_tarefas",
    iconName: "ClipboardText",
  },
  {
    id: "documentos",
    title: "Central de Documentos",
    description: "Upload e aprovação de documentos de propostas e apólices.",
    keywords: ["documentos", "anexos", "documentação", "rg", "cpf", "comprovante"],
    url: "/documentos",
    domain: "Operação",
    permission: "acessar_documentos",
    iconName: "Note",
  },
  {
    id: "catalogo",
    title: "Catálogo Global de Planos",
    description: "Consulta de tabelas de operadoras, carências e regras de coparticipação.",
    keywords: ["catálogo", "planos", "operadoras", "bradesco", "sulamerica", "amil", "carências"],
    url: "/catalogo",
    domain: "Operação",
    permission: "acessar_catalogo",
    iconName: "FolderSimple",
  },
  {
    id: "noc",
    title: "NOC & Alertas de Rede",
    description: "Monitoramento de infraestrutura de comunicação, filas e conexões WhatsApp.",
    keywords: ["noc", "alertas", "infraestrutura", "status", "saúde"],
    url: "/noc",
    domain: "Operação",
    permission: "ver_dashboard_equipe",
    iconName: "Monitor",
  },
  {
    id: "marketing",
    title: "Marketing & Campanhas Meta",
    description: "Gestão de anúncios, formulários de Lead Ads e materiais de vendas.",
    keywords: ["marketing", "campanhas", "meta ads", "facebook", "instagram", "materiais"],
    url: "/marketing",
    domain: "Administração",
    permission: "acessar_campanhas_meta",
    iconName: "Megaphone",
  },
  {
    id: "filiais",
    title: "Unidades & Filiais",
    description: "Cadastro de filiais da corretora e distribuição regional.",
    keywords: ["filiais", "unidades", "endereços", "regiões", "escritórios"],
    url: "/filiais",
    domain: "Administração",
    permission: "gerenciar_filiais",
    iconName: "Buildings",
  },
  {
    id: "settings",
    title: "Parâmetros & Comissões",
    description: "Configurações gerais do tenant, integração Meta, perfil e tabela de comissões.",
    keywords: ["configurações", "parâmetros", "comissões", "integrações", "perfil", "tenant"],
    url: "/settings",
    domain: "Administração",
    permission: "acessar_configuracoes_pessoais",
    iconName: "SlidersHorizontal",
  },
  {
    id: "settings_comissoes",
    title: "Tabela de Comissões",
    description: "Configuração dos percentuais e regras de comissionamento por produto.",
    keywords: ["comissão", "comissões", "tabela de comissões", "repasse", "bonificação"],
    url: "/settings?tab=comissoes",
    domain: "Administração",
    permission: "gerenciar_comissoes",
    iconName: "CurrencyCircleDollar",
  },
  {
    id: "guia",
    title: "Guia & Central de Ajuda",
    description: "Manual do sistema, glossário de termos e tutoriais passo a passo.",
    keywords: ["guia", "ajuda", "glossário", "suporte", "manual", "como funciona"],
    url: "/guia",
    domain: "Administração",
    permission: "acessar_guia",
    iconName: "BookOpen",
  },
];
