import type { Tour } from "nextstepjs";

export const brokerTours: Tour[] = [
  {
    tour: "broker-welcome",
    steps: [
      {
        icon: "👋",
        title: "Bem-vindo ao Âncora CRM",
        content: "Acompanhe seus leads, atendimentos, tarefas, cotações e documentos em um único lugar.",
        showControls: true,
        showSkip: true,
        pointerRadius: 12,
      },
      {
        icon: "📥",
        title: "Fila de Oportunidades",
        content: "Os novos leads atribuídos à sua carteira ou plantão aparecem nesta área.",
        selector: '[data-onboarding="lead-queue"]',
        side: "top",
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
        selectorRetryAttempts: 10,
        selectorRetryDelay: 100,
        scrollOffset: 60,
      },
      {
        icon: "⏱️",
        title: "Prioridade & SLA",
        content: "Os marcadores de SLA indicam quanto tempo resta para realizar o primeiro atendimento.",
        selector: '[data-onboarding="sla-indicator"]',
        side: "bottom",
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 10,
        selectorRetryAttempts: 10,
        selectorRetryDelay: 100,
        scrollOffset: 60,
      },
      {
        icon: "✅",
        title: "Agenda & Tarefas do Dia",
        content: "Seus retornos, lembretes de ligação e compromissos ficam organizados aqui.",
        selector: '[data-onboarding="daily-tasks"]',
        side: "top",
        showControls: true,
        showSkip: true,
        pointerPadding: 8,
        pointerRadius: 12,
        selectorRetryAttempts: 10,
        selectorRetryDelay: 100,
        scrollOffset: 60,
      },
    ],
  },
  {
    tour: "broker-lead-profile",
    steps: [
      {
        icon: "👤",
        title: "Perfil Completo do Lead",
        content: "Consulte dados pessoais, histórico de interações, origem e perfil familiar.",
        selector: '[data-onboarding="lead-profile"]',
        side: "right",
        showControls: true,
        showSkip: true,
        selectorRetryAttempts: 10,
        selectorRetryDelay: 100,
        scrollOffset: 60,
      },
      {
        icon: "💬",
        title: "Linha do Tempo de Atendimento",
        content: "Veja mensagens trocadas, observações gravadas e respostas automáticas da IA.",
        selector: '[data-onboarding="lead-timeline"]',
        side: "left",
        showControls: true,
        showSkip: true,
        selectorRetryAttempts: 10,
        selectorRetryDelay: 100,
        scrollOffset: 60,
      },
      {
        icon: "📅",
        title: "Agendar Próximo Contato",
        content: "Crie uma tarefa de retorno com data e hora para nunca perder um acompanhamento.",
        selector: '[data-onboarding="create-follow-up"]',
        side: "top",
        showControls: true,
        showSkip: true,
        selectorRetryAttempts: 10,
        selectorRetryDelay: 100,
        scrollOffset: 60,
      },
    ],
  },
  {
    tour: "broker-quotation",
    steps: [
      {
        icon: "🧾",
        title: "Simulação de Cotação",
        content: "Informe quantidade de vidas e idades dos beneficiários para comparar operadoras.",
        selector: '[data-onboarding="quote-beneficiaries"]',
        side: "right",
        showControls: true,
        showSkip: true,
        selectorRetryAttempts: 10,
        selectorRetryDelay: 100,
        scrollOffset: 60,
      },
      {
        icon: "🔎",
        title: "Comparativo de Planos",
        content: "Analise valores de mensalidades, rede credenciada e carências de cada produto.",
        selector: '[data-onboarding="quote-results"]',
        side: "top",
        showControls: true,
        showSkip: true,
        selectorRetryAttempts: 10,
        selectorRetryDelay: 100,
        scrollOffset: 60,
      },
      {
        icon: "📄",
        title: "Gerar Proposta Comercial",
        content: "Exporte a cotação em PDF personalizado para envio imediato ao cliente.",
        selector: '[data-onboarding="generate-quote-pdf"]',
        side: "left",
        showControls: true,
        showSkip: true,
        selectorRetryAttempts: 10,
        selectorRetryDelay: 100,
        scrollOffset: 60,
      },
    ],
  },
];
