declare module 'react-aria-components' {
  export const Focusable: any;
  export const Checkbox: any;
  export type CheckboxProps = any;
  export const Text: any;
  export type TextProps = any;
  export const TextField: any;
  export type TextFieldProps = any;
  export const Input: any;
  export type InputProps = any;
  export const Label: any;
  export type LabelProps = any;
  export const ToggleButtonGroup: any;
  export type ToggleButtonGroupProps = any;
  export const ToggleButton: any;
  export type ToggleButtonProps = any;
  export const Select: any;
  export type SelectProps<T = any> = any;
  export type SelectValueRenderProps<T = any> = any;
  export const ListBoxItem: any;
  export type ListBoxItemProps<T = any> = any;
  export const Table: any;
  export type TableProps = any;
  export const Tooltip: any;
  export type TooltipProps = any;
  export const Group: any;
  export const Button: any;
  export const DialogTrigger: any;
  export const Popover: any;
  export const Dialog: any;
  export const MenuTrigger: any;
  export const Menu: any;
  export const MenuItem: any;
  export const Header: any;
  export const Section: any;
  export const SelectValue: any;
  export const ListBox: any;
  export const TableHeader: any;
  export const Column: any;
  export const TableBody: any;
  export const Row: any;
  export const Cell: any;
  export const OverlayArrow: any;
  export const TooltipTrigger: any;
  export type AriaCheckboxProps = any;
  export type AriaTextProps = any;
  export type AriaTextFieldProps = any;
  export type AriaInputProps = any;
  export type AriaLabelProps = any;
  export type AriaToggleButtonGroupProps = any;
  export type AriaToggleButtonProps = any;
  export type AriaSelectProps<T = any> = any;
  export type AriaSelectValueRenderProps<T = any> = any;
  export type AriaListBoxItemProps<T = any> = any;
  export type AriaTableProps = any;
  export type AriaTooltipProps = any;
  export type AriaPopoverProps = any;
}
