export type DataTableConfig = typeof dataTableConfig;

export const dataTableConfig = {
  comparisonOperators: [
    { label: "Contém", value: "iLike" as const },
    { label: "Não contém", value: "notILike" as const },
    { label: "É igual a", value: "eq" as const },
    { label: "É diferente de", value: "ne" as const },
    { label: "Está em", value: "inArray" as const },
    { label: "Não está em", value: "notInArray" as const },
    { label: "Está vazio", value: "isEmpty" as const },
    { label: "Não está vazio", value: "isNotEmpty" as const },
    { label: "Menor que", value: "lt" as const },
    { label: "Menor ou igual", value: "lte" as const },
    { label: "Maior que", value: "gt" as const },
    { label: "Maior ou igual", value: "gte" as const },
    { label: "Entre", value: "isBetween" as const },
    { label: "Relativo a hoje", value: "isRelativeToToday" as const },
  ],
  filterVariants: [
    "text",
    "number",
    "range",
    "date",
    "dateRange",
    "boolean",
    "select",
    "multiSelect",
  ] as const,
  operators: [
    "iLike",
    "notILike",
    "eq",
    "ne",
    "inArray",
    "notInArray",
    "isEmpty",
    "isNotEmpty",
    "lt",
    "lte",
    "gt",
    "gte",
    "isBetween",
    "isRelativeToToday",
  ] as const,
  joinOperators: ["and", "or"] as const,
  textOperators: [
    { label: "Contém", value: "iLike" as const },
    { label: "Não contém", value: "notILike" as const },
    { label: "É igual a", value: "eq" as const },
    { label: "É diferente de", value: "ne" as const },
    { label: "Está vazio", value: "isEmpty" as const },
    { label: "Não está vazio", value: "isNotEmpty" as const },
  ],
  numberOperators: [
    { label: "É igual a", value: "eq" as const },
    { label: "É diferente de", value: "ne" as const },
    { label: "Menor que", value: "lt" as const },
    { label: "Menor ou igual", value: "lte" as const },
    { label: "Maior que", value: "gt" as const },
    { label: "Maior ou igual", value: "gte" as const },
    { label: "Entre", value: "isBetween" as const },
    { label: "Está vazio", value: "isEmpty" as const },
    { label: "Não está vazio", value: "isNotEmpty" as const },
  ],
  dateOperators: [
    { label: "É igual a", value: "eq" as const },
    { label: "Antes de", value: "lt" as const },
    { label: "Depois de", value: "gt" as const },
    { label: "Entre datas", value: "isBetween" as const },
    { label: "Relativo a hoje", value: "isRelativeToToday" as const },
    { label: "Está vazio", value: "isEmpty" as const },
    { label: "Não está vazio", value: "isNotEmpty" as const },
  ],
  selectOperators: [
    { label: "É um de", value: "inArray" as const },
    { label: "Não é um de", value: "notInArray" as const },
    { label: "Está vazio", value: "isEmpty" as const },
    { label: "Não está vazio", value: "isNotEmpty" as const },
  ],
  booleanOperators: [
    { label: "É igual a", value: "eq" as const },
    { label: "É diferente de", value: "ne" as const },
  ],
};
